"use client";

import { Artwork, Tag } from "@prisma/client";
import Image from "next/image";
import Link from "next/link";

// Extends the default Artwork type generated by Prisma to include the `tags` relation.
interface ArtworkWithTags extends Artwork {
  tags: Tag[];
}

/**
 * A component that renders a single artwork as a clickable card.
 * It displays the image, title, and associated tags.
 * When a user hovers over the card, the image has a subtle zoom effect.
 */
export default function ArtworkItem({ artwork }: { artwork: ArtworkWithTags }) {
  // The entire card is a link to a future detailed artwork page.
  // The link is currently a placeholder pointing to the artwork's ID.
  return (
    <div className="border border-cyan-400/30 rounded-lg overflow-hidden group transition-all duration-300 hover:border-cyan-400/80 hover:shadow-lg hover:shadow-cyan-500/50">
      <Link href={`/artwork/${artwork.id}`}>
        <div className="relative aspect-square overflow-hidden">
          <Image
            src={artwork.imageUrl}
            alt={artwork.title}
            fill
            sizes="(max-width: 640px) 100vw, (max-width: 768px) 50vw, (max-width: 1024px) 33vw, 25vw"
            className="object-cover transition-transform duration-300 group-hover:scale-110"
          />
        </div>
        <div className="p-4 bg-gray-800/50">
          <h3 className="text-xl font-bold text-white truncate">{artwork.title}</h3>
          <div className="flex flex-wrap gap-2 mt-2">
            {artwork.tags.map((tag) => (
              <span key={tag.id} className="px-2 py-1 bg-gray-700 text-cyan-400 rounded-md text-sm">
                #{tag.name}
              </span>
            ))}
          </div>
        </div>
      </Link>
    </div>
  );
}

